version: '3'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8001:80"
    environment:
      - PHPIDS_ENABLE=true
    restart: unless-stopped

  bwapp:
    image: raesene/bwapp
    ports:
      - "8002:80"
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    restart: unless-stopped

  metasploitable2:
    image: tleemcjr/metasploitable2
    ports:
      - "21:21"
      - "22:22"
      - "23:23"
      - "80:80"
      - "445:445"
      - "3306:3306"
      - "5432:5432"
    restart: unless-stopped

networks:
  internal:
    driver: bridge
